"""user templates

Revision ID: 0002_registry
Revises: 0001_registry
Create Date: 2026-09-30 05:09:42.837122
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002_registry'
down_revision = '0001_registry'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_templates'))
    )
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_templates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_templates_user_id'))

    op.drop_table('user_templates')
    # ### end Alembic commands ###
