"""agent org fields and company revision

Revision ID: 0002_project
Revises: 0001_project
Create Date: 2026-09-30 05:09:42.885944
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002_project'
down_revision = '0001_project'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=80), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('is_manager', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('reports_to', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('revision')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('created_by')
        batch_op.drop_column('active')
        batch_op.drop_column('reports_to')
        batch_op.drop_column('is_manager')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
